### ISSUE TITLE
Undefined variable: "$heading-font-family".

### ISSUE THREAD

**Issue by Christilut** [nmsmith22389/vuetify-scss#1]
Hey, thanks for this, just what I needed for Vuetify.

I'm getting this error after installing and running it:
```
Undefined variable: "$heading-font-family".
```

I've added that variable as a dirty fix in _variables.scss and that works but not sure what the real fix is for this.

**Comment by nmsmith22389** [comment]
Hey! Thank's I'm glad you like it! I'm sorry about the bug. I'll go in and fix it for the next release.

Thanks! 😁

**Comment by nmsmith22389** [comment]
Fixed in [v1.0.1](https://github.com/nmsmith22389/vuetify-scss/releases/tag/v1.0.1).
