### ISSUE TITLE
Dude, You just broke it

### ISSUE THREAD

**Issue by jacklp** [nmsmith22389/vuetify-scss#10]
![screenshot 2019-02-05 at 14 48 45](https://user-images.githubusercontent.com/877409/52281761-adb8b380-2956-11e9-8e3b-8e442b001d7c.png)

Needs a comma methinks

**Comment by nmsmith22389** [comment]
Sorry! 😵

I missed a few things in `/settings/_variables.scss` in my rush to finally update everything.
I've merged both of your PRs. Thank you for the help! 🎉

_PS_
_Feel free to comment, suggest, PR with other stuff! I could always use the help!_

**Comment by larsenwork** [comment]
Could you bump it to 1.3.6 on npm too?
