### ISSUE TITLE
You broke it again ><

### ISSUE THREAD

**Issue by jacklp** [nmsmith22389/vuetify-scss#14]
in vuetify-scss/components/_icons.scss - Please remove the following blocks of code:

`
    &--right {
        margin-left: map-get($grid-gutters, lg);
    }
`
`
    &--left {
        margin-right: map-get($grid-gutters, lg);
    }
`
`
    &--disabled {
        opacity: 0.6;
        pointer-events: none;
    }
`
`
    &--is-component {
        height: rem(24px);
    }
`

The above styles are _invalid_ code as specified by the following error message:

> Failed to compile.
> 
> ./src/styles/index.scss (./node_modules/css-loader??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-3-3!./src/styles/index.scss)
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
>     &--right {
>    ^
>       Invalid parent selector ":not(.svg-inline--fa)"
>    ╷
> 31 │     &--right {
>    │     ^^^^^^^^^
>    ╵
>   node_modules/vuetify-scss/components/_icons.scss 31:5  @import
>   node_modules/vuetify-scss/components/_all.scss 29:9    @import
>   node_modules/vuetify-scss/main.scss 2:9                @import
>   stdin 1:10                                             root stylesheet
>       in /Users/jackprior/work/OpsAdmin/SF.Services.OpsAdmin.UI/node_modules/vuetify-scss/components/_icons.scss (line 31, column 5)

**Comment by nmsmith22389** [comment]
Sorry!

For some reason the error wasn't happening when I was transpiling it so I didn't see it at first. Then, I got held up working on a project for a client. I've got a fix coming out in literally a minute or two so hold tight!
