### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by faebeee** [nmsmith22389/vuetify-scss#16]
Is this repository/project actively developed or whats the status on this?

**Comment by nmsmith22389** [comment]
Yeah it's active for the most part. I've just been busy doing work for a client so I haven't had the chance to update it yet.

I'll update it and also merge your PR.

**Comment by nmsmith22389** [comment]
I just wanted to add...

If you ever have any other ideas for features or improvements please feel free to open an issue or PR and we can discuss them. Thanks! 🤓
