### ISSUE TITLE
Problems using vue-cli and run build -> the minification fails with "CSS minification error"

### ISSUE THREAD

**Issue by jan-johansson-mr** [nmsmith22389/vuetify-scss#2]
Hi,

Thanks for scss for vuetify!

I'm happy to use the vuetify-scss, but for some reason I can't build a production release. The error I get is:
` ERROR  Error: CSS minification error: Lexical error on line 1. Unrecognized text. -50%, - 1px`, and it happens with `node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21`.

It's very easy to reproduce.

Create a vue project, I use typescript template, but it doesn't matter what template. Use the import line: ` @import "~vuetify-scss";` with e.g. `App.vue` and within the `<style lang="scss">` section. Then do `npm run build` and you get the error.

However, `npm run serve` works just fine!

I'm running `vue-cli 3.0.0-rc.10`.

Thanks,
//Jan

**Comment by nmsmith22389** [comment]
It was actually an error in Vuetify's code. I'm not really sure why they have it like that... they probably just missed it.

Either way it's fixed in [v1.0.3](https://github.com/nmsmith22389/vuetify-scss/releases/tag/v1.0.3). Thanks!
