### ISSUE TITLE
Minor Scss syntax issues breaking a few Vuetify Styles

### ISSUE THREAD

**Issue by samnau** [nmsmith22389/vuetify-scss#4]
`_content.scss` : line 11, "--wrap" should be "__wrap"
`theme.scss`: lines 5 & 12 have an extra space. ".application .theme--dark.#{$name}" should be ".application.theme--light.#{$name}" and .application.theme--dark.#{$name}

**Comment by nmsmith22389** [comment]
Hey! Sorry I've been really busy lately so the package has fallen behind the development of Veutify. I'm working on catching it back up right now. Those changes were introduced in Vuetify@v1.2.0 so once this package catches up it should be all fixed. Just keep an eye out for the newer versions! Thanks!
