### ISSUE TITLE
Halp.. getting error on build.

### ISSUE THREAD

**Issue by rogerriche** [nmsmith22389/vuetify-scss#8]
getting this when attempting to build with npm run dev:

ERROR in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/lib/loader.js??ref--6-5!./resources/sass/builder.scss
Module build failed: 
        background: map-get($material, $dividers);

halp?  I love what you are doing here and prefer sass over stylus.

**Comment by rogerriche** [comment]
I did create a _vuetify_vars that I've imported first.. seemed that it's complaining about several things that I've set to false for now:

$dividers: false;
$cards: false;

**Comment by rogerriche** [comment]
Another odd thing is the look is not the same as what I would expect out of defaults from veutify.

For example, my input is looking like this. colors and font are different??

![image](https://user-images.githubusercontent.com/7675086/47406759-b3262100-d70c-11e8-8bfc-b7e325692b03.png)

**Comment by nmsmith22389** [comment]
Yea that's my bad... I messed up the bug fix and now there's a typo... I'm updating it literally right now and will deprecate the latest version. Hold tight for just a minute then try updating to the newest version.

**Comment by nmsmith22389** [comment]
**Fixed in [v1.2.3](https://github.com/nmsmith22389/vuetify-scss/releases/tag/v1.2.3)** (fda5d80)

Try this fix... Let me know if you have any more problem.

Thanks!

**Comment by rogerriche** [comment]
all good now captain! thanks . love it and thanks so much for your awesomeness.

**Comment by nmsmith22389** [comment]
No problem! Glad someone appreciates it! 😁
