### ISSUE TITLE
Overriding default variables

### ISSUE THREAD

**Issue by benmcm1994** [nmsmith22389/vuetify-scss#9]
Hi,

I noticed I couldn't override the default `$body-font-family` variable using `@import 'variables'` due to a `File to import not found` error. 

Instead of doing `@import 'variables'` as described in the current Readme, I simply imported the variables file via **`@import '~vuetify-scss/settings/variables';`** which works perfectly.

Just posting in case anyone else ran into this problem.

**Comment by rogerriche** [comment]
you have to create your own variables file to use for overriding.

**Comment by benmcm1994** [comment]
> you have to create your own variables file to use for overriding.

Yes, I do this in my `styles/main.scss`. Not much other more than overriding default fonts and some other things will be here.

**Comment by nmsmith22389** [comment]
I'm sorry I should make the documentation more clear. Like @rogerriche said, the `@import 'variables';` reference in the readme refers to your own variables file. The one in the vuetify-scss settings folder declares variables with the `! default'` flag so they can be overridden by your own variables file. Perhaps in the future I can include a _template_ variables file you can copy over or something but until then you need to just make your own and override the variables you wish to change.

I hope that clears things up. If you have any more problems just let me know.

Thanks! 😁 

_P.S. I should also note that if you don't want the variable overrides to be in your main variables file, they don't have to be in a specifically named file like `_variables.scss`. It could be `_vuetify-vars.scss` or anything you want. Just make sure you don't include the `!default` flag like in the package._
